apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-gitops
  labels:
    app: hello-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-gitops
  template:
    metadata:
      labels:
        app: hello-gitops
    spec:
      containers:
      - name: hello-gitops
        image: feketej/hello-gitops
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 128Mi
        ports:
        - containerPort: 8080
